export const us_states = [
  { label: "AL", value: "al" },
  { label: "AK", value: "ak" },
  { label: "AZ", value: "az" },
  { label: "AR", value: "ar" },
  { label: "CA", value: "ca" },
  { label: "CO", value: "co" },
  { label: "CT", value: "ct" },
  { label: "DE", value: "de" },
  { label: "FL", value: "fl" },
  { label: "GA", value: "ga" },
  { label: "HI", value: "hi" },
  { label: "ID", value: "id" },
  { label: "IL", value: "il" },
  { label: "IN", value: "in" },
  { label: "IA", value: "ia" },
  { label: "KS", value: "ks" },
  { label: "KY", value: "ky" },
  { label: "LA", value: "la" },
  { label: "ME", value: "me" },
  { label: "MD", value: "md" },
  { label: "MA", value: "ma" },
  { label: "MI", value: "mi" },
  { label: "MN", value: "mn" },
  { label: "MS", value: "ms" },
  { label: "MO", value: "mo" },
  { label: "MT", value: "mt" },
  { label: "NE", value: "ne" },
  { label: "NV", value: "nv" },
  { label: "NH", value: "nh" },
  { label: "NJ", value: "nj" },
  { label: "NM", value: "nm" },
  { label: "NY", value: "ny" },
  { label: "NC", value: "nc" },
  { label: "ND", value: "nd" },
  { label: "OH", value: "oh" },
  { label: "OK", value: "ok" },
  { label: "OR", value: "or" },
  { label: "PA", value: "pa" },
  { label: "RI", value: "ri" },
  { label: "SC", value: "sc" },
  { label: "SD", value: "sd" },
  { label: "TN", value: "tn" },
  { label: "TX", value: "tx" },
  { label: "UT", value: "ut" },
  { label: "VT", value: "vt" },
  { label: "VA", value: "va" },
  { label: "WA", value: "wa" },
  { label: "WV", value: "wv" },
  { label: "WI", value: "wi" },
  { label: "WY", value: "wy" },
];

export const countries = [
  { label: "Argentina", value: "argentina" },
  { label: "Australia", value: "australia" },
  { label: "Austria", value: "austria" },
  { label: "Belgium", value: "belgium" },
  { label: "Brazil", value: "brazil" },
  { label: "Canada", value: "canada" },
  { label: "China", value: "china" },
  { label: "Czech Republic", value: "czech_republic" },
  { label: "Denmark", value: "denmark" },
  { label: "Egypt", value: "egypt" },
  { label: "Finland", value: "finland" },
  { label: "France", value: "france" },
  { label: "Germany", value: "germany" },
  { label: "Greece", value: "greece" },
  { label: "Hungary", value: "hungary" },
  { label: "India", value: "india" },
  { label: "Indonesia", value: "indonesia" },
  { label: "Ireland", value: "ireland" },
  { label: "Israel", value: "israel" },
  { label: "Italy", value: "italy" },
  { label: "Japan", value: "japan" },
  { label: "Kenya", value: "kenya" },
  { label: "Malaysia", value: "malaysia" },
  { label: "Mexico", value: "mexico" },
  { label: "Netherlands", value: "netherlands" },
  { label: "New Zealand", value: "new_zealand" },
  { label: "Nigeria", value: "nigeria" },
  { label: "Norway", value: "norway" },
  { label: "Philippines", value: "philippines" },
  { label: "Poland", value: "poland" },
  { label: "Portugal", value: "portugal" },
  { label: "Russia", value: "russia" },
  { label: "Saudi Arabia", value: "saudi_arabia" },
  { label: "Singapore", value: "singapore" },
  { label: "South Africa", value: "south_africa" },
  { label: "South Korea", value: "south_korea" },
  { label: "Spain", value: "spain" },
  { label: "Sweden", value: "sweden" },
  { label: "Switzerland", value: "switzerland" },
  { label: "Thailand", value: "thailand" },
  { label: "Turkey", value: "turkey" },
  { label: "United Arab Emirates", value: "united_arab_emirates" },
  { label: "United Kingdom", value: "united_kingdom" },
  { label: "United States", value: "united_states" },
  { label: "Vietnam", value: "vietnam" },
];

export const cancellation_reasons = [
  {
    label: "The job or service is not what I expected",
    value: "not_expected",
  },
  { label: "I am unavailable for the job", value: "unavailable" },
  { label: "I do not want to work with this user", value: "user" },
  { label: "I do not want to provide the reason", value: "ommitted" },
  { label: "Other", value: "other" },
];

export const explore_categories = [
  {
    label: "Tech",
    value: "tech",
    image: require(`@/assets/images/explore/category-tech.jpg`),
  },
  {
    label: "Health",
    value: "health",
    image: require(`@/assets/images/explore/category-health.jpg`),
  },
  {
    label: "Home",
    value: "home",
    image: require(`@/assets/images/explore/category-home.jpg`),
  },
  {
    label: "Food",
    value: "food",
    image: require(`@/assets/images/explore/category-food.jpg`),
  },
  {
    label: "Education",
    value: "education",
    image: require(`@/assets/images/explore/category-education.jpg`),
  },
  {
    label: "Gaming",
    value: "gaming",
    image: require(`@/assets/images/explore/category-gaming.jpg`),
  },
];

export const notification_titles = {
  accepted: (username: string) => ({
    title: `Job accepted by ${username}!`,
    description: "Open Hustle to view more.",
  }), // for hirer
  approved: (username: string) => ({
    title: `Approved by ${username}!`,
    description: "Open Hustle to view more.",
  }), // for worker
  in_progress: (username: string) => ({
    title: `Job by ${username} in progress!`,
    description: "Open Hustle to view more.",
  }), // for hirer
  complete: (username: string) => ({
    title: `Job by ${username} completed!`,
    description: "Open Hustle to view more.",
  }), // for hirer
  paid: (username: string) => ({
    title: `${username} paid you!`,
    description: "Open Hustle to view more.",
  }), // for worker
  cancelled: (username: string) => ({
    title: `Job cancelled by ${username}.`,
    description: "Open Hustle to view more.",
  }), // for hirer or worker
};
